name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config --global user.email "soumy99sharma@gmail.com"
          git config --global user.name "Soumy Sharma"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          echo "${DEPLOY_KEY}" > deploy_key
          chmod 600 deploy_key
          eval $(ssh-agent -s)
          ssh-add deploy_key
          git remote set-url origin git@github.com:${{ github.repository }}.git
          npm run deploy
