name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "soumy99sharma@gmail.com"
          git config --global user.name "Soumy Sharma"

      - name: Install dependencies
        run: npm install

      - name: Run npm commands
        run: npm run deploy -- -m "Deploy React app to GitHub Pages"
          # Add more npm commands as needed
